server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Enable gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # First attempt to serve request as file, then
    # serve index.html
    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Specific rule for .html files
    location ~ \.html$ {
        try_files $uri =404;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}